version: "3.9"
services:
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_USER: vertx
      MYSQL_DATABASE: books
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - 'mysql:db'
    ports:
      - '8081:80'
  api-test:
    image: api-test:1
    container_name: api-test
    restart: always
    working_dir: "/usr/verticles"
    deploy:
      resources:
        limits:
          memory: 1024m
    depends_on:
      - mysql
    links:
      - 'mysql:db'
    expose:
      - "8080"
      - "8000"
    ports:
      - "9001:8888"
      - "8085:8085"
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql:3306/books
      DATASOURCE_USERNAME: vertx
      DATASOURCE_PASSWORD: password

