version: "3.9"
services:
  mysql:
    image: mariadb:latest
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: vertx
      MYSQL_DATABASE: books
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - 'mysql:db'
    ports:
      - '8081:80'


